#ifdef CONFIG_MQTT_URL
#define MQTT_URL CONFIG_MQTT_URL
#endif

#ifdef CONFIG_MQTT_IP_ADDRESS_WITH_PORT
#define MQTT_IP_ADDRESS_WITH_PORT CONFIG_MQTT_IP_ADDRESS_WITH_PORT
#else
#define MQTT_IP_ADDRESS_WITH_PORT "mqtt://3.19.24.164:1883"
#endif

#ifdef CONFIG_MQTT_CLIENT_ID
#define MQTT_CLIENT_ID CONFIG_MQTT_CLIENT_ID
#else
#define MQTT_CLIENT_ID "client"
#endif

#ifdef CONFIG_MQTT_USERNAME
#define MQTT_USERNAME CONFIG_MQTT_USERNAME
#else
#define MQTT_USERNAME "user"
#endif

#ifdef CONFIG_MQTT_PASSWORD
#define MQTT_PASSWORD CONFIG_MQTT_PASSWORD
#else
#define MQTT_PASSWORD "password"
#endif
